version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Clean
          command: make clean
      - run:
          name: Dependencies
          command: make dependencies
      - run:
          name: Lint
          command: make lint
      - run:
          name: Unit tests
          command: make test-unit
      - run:
          name: Build
          command: make build
      - run:
          name: Tag & push images
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              docker login docker.wouterdeschuyter.be -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
              make tag
              make push
              make push-latest
            else
              echo "Not master branch, skipping"
            fi
      - run:
          name: Deploy
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              echo "Todo"
            else
              echo "Not master branch, skipping"
            fi
