version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Clean
          command: make clean
      - run:
          name: Dependencies
          command: make dependencies
      - run:
          name: Lint
          command: make lint
      - run:
          name: Build
          command: make build
      - run:
          name: Unit tests
          command: make tests-unit
      - run:
          name: Push
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              echo "Todo"
            else
              echo "Not master branch, skipping"
            fi
      - run:
          name: Deploy
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              echo "Todo"
            else
              echo "Not master branch, skipping"
            fi
