version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Clean
          command: make clean
      - run:
          name: Dependencies
          command: make dependencies
      - run:
          name: Lint
          command: make lint
      - run:
          name: Unit tests
          command: make test-unit
      - run:
          name: Build
          command: make build
      - run:
          name: Tag & push images
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              docker login docker.wouterdeschuyter.be -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
              make tag
              make push
              make push-latest
            else
              echo "Not master branch, skipping"
            fi
      - run:
          name: Deploy
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              ssh $USER@$SERVER "mkdir -p $LOCATION"
              ssh $USER@$SERVER "mkdir -p $LOCATION/logs && chmod 777 $LOCATION/logs"
              ssh $USER@$SERVER "mkdir -p $LOCATION/media && chmod 777 $LOCATION/media"

              scp ./.docker/docker-compose.yml $USER@$SERVER:$LOCATION/docker-compose.yml
              scp ./.docker/docker-compose-prod.yml $USER@$SERVER:$LOCATION/docker-compose-prod.yml
              scp ./.docker/docker.env $USER@$SERVER:$LOCATION/docker.env

              ssh $USER@$SERVER "cd $LOCATION; docker-compose -f docker-compose.yml -f docker-compose-prod.yml pull"
              ssh $USER@$SERVER "cd $LOCATION; docker-compose -f docker-compose.yml -f docker-compose-prod.yml down --volume"
              ssh $USER@$SERVER "cd $LOCATION; docker-compose -f docker-compose.yml -f docker-compose-prod.yml up -d"

              ssh $USER@$SERVER "docker exec $CONTAINER_php-cron_1 php ./composer.phar migrations:migrate"
              ssh $USER@$SERVER "docker exec $CONTAINER_php-cron_1 php ./console/app generate:sitemap"
              ssh $USER@$SERVER "docker exec $CONTAINER_php-cron_1 php ./console/app generate:robots"
              ssh $USER@$SERVER "docker exec $CONTAINER_php-cron_1 php ./console/app generate:rss"
              ssh $USER@$SERVER "docker exec $CONTAINER_php-cron_1 php ./console/app blog:generate-structured-data"
            else
              echo "Not master branch, skipping"
            fi
