version: '2'

services:
  nginx:
    image: nginx:1.13-alpine
    container_name: wouterdeschuyter-website-nginx
    env_file:
      - ./../.env
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./../public:/code/public

  php-fpm:
    image: php:7.1-fpm-alpine
    container_name: wouterdeschuyter-website-php-fpm
    env_file:
      - ./../.env
    volumes:
      - ./..:/code

  mysql:
    image: mysql:5.7
    container_name: wouterdeschuyter-website-mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - ./../.env
    ports:
      - "3306:3306"
