version: '2'

services:
  nginx:
    image: docker.wouterdeschuyter.be/internal-wouterdeschuyter-website-nginx
    restart: unless-stopped
    env_file:
      - docker.env
    environment:
      - LETSENCRYPT_EMAIL=wouter@wouterdeschuyter.be
    volumes:
      - ./media:/code/storage/media
    networks:
      - default
      - nginxproxy_default

  php-fpm:
    image: docker.wouterdeschuyter.be/internal-wouterdeschuyter-website-php-fpm
    restart: unless-stopped
    env_file:
      - docker.env
    volumes_from:
      - nginx
    volumes:
      - ./logs:/code/storage/logs
    external_links:
      - mariadb
    networks:
      - default
      - databaseserver_default

networks:
  databaseserver_default:
    external: true
  nginxproxy_default:
    external: true
