version: '2'

services:
  nginx-web:
    image: docker.wouterdeschuyter.be/internal-wouterdeschuyter-website-nginx-web
    restart: unless-stopped
    env_file: docker-prod.env
    environment:
      - VIRTUAL_HOST=wouterdeschuyter.be
      - LETSENCRYPT_HOST=wouterdeschuyter.be
      - LETSENCRYPT_EMAIL=wouter@wouterdeschuyter.be
    networks:
      - default
      - nginxproxy_default

  php-fpm:
    image: docker.wouterdeschuyter.be/internal-wouterdeschuyter-website-php-fpm
    restart: unless-stopped
    env_file: docker-prod.env
    volumes:
      - ./docker-prod.env:/code/.env:ro
      - ./logs:/code/storage/logs
    external_links:
      - mariadb
    networks:
      - default
      - databaseserver_default

networks:
  databaseserver_default:
    external: true
  nginxproxy_default:
    external: true
