version: '2'

services:
  nginx:
    image: docker.wouterdeschuyter.be/wouterdeschuyter-website-nginx
    restart: unless-stopped
    env_file:
      - docker.env
    environment:
      - LETSENCRYPT_EMAIL=wouter@wouterdeschuyter.be
    volumes:
      - /code/public
      - ./media:/code/storage/media
      - ./logs/nginx:/logs
    networks:
      - default
      - webproxy
    logging:
      options:
        max-size: 2m
        max-file: '5'

  php-fpm:
    image: docker.wouterdeschuyter.be/wouterdeschuyter-website-php-fpm
    restart: unless-stopped
    env_file:
      - docker.env
    volumes_from:
      - nginx
    volumes:
      - ./logs:/code/storage/logs
    networks:
      - default
      - mariadb
    logging:
      options:
        max-size: 2m
        max-file: '5'

  php-cron:
    image: docker.wouterdeschuyter.be/wouterdeschuyter-website-php-cron
    restart: unless-stopped
    volumes_from:
      - php-fpm
    env_file:
      - docker.env
    networks:
      - default
      - mariadb
    logging:
      options:
        max-size: 2m
        max-file: '5'

networks:
  mariadb:
    external: true
  webproxy:
    external: true
