version: '2'

services:
  nginx:
    image: nginx:alpine
    container_name: wouterdeschuyter-website-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./../public:/code/public
      - ./../storage/media:/code/storage/media
      - ./../storage/logs/nginx:/logs
    env_file:
      - ./../.env
    ports:
      - '80:80'

  php-cron:
    build:
      context: ./..
      dockerfile: ./.docker/php-cron/Dockerfile
    container_name: wouterdeschuyter-website-php-cron
    volumes_from:
      - nginx
    volumes:
      - ./..:/code
      - ./../storage/logs:/code/storage/logs
      - ./../storage/media:/code/storage/media
    env_file:
      - ./../.env

  php-fpm:
    build:
      context: ./..
      dockerfile: ./.docker/php-fpm/Dockerfile
    container_name: wouterdeschuyter-website-php-fpm
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./..:/code
      - ./../storage/logs:/code/storage/logs
      - ./../storage/media:/code/storage/media
    env_file:
      - ./../.env

  mysql:
    image: mysql:5.7
    container_name: wouterdeschuyter-website-mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - ./../.env
    ports:
      - '3306:3306'
