#!/usr/bin/env php
<?php

use Dotenv\Dotenv;
use Tracy\Debugger;

// Application directory
define('APP_DIR', dirname(__DIR__));

// Include composer autoloader
require_once APP_DIR . '/vendor/autoload.php';

// Debugger mode
$debuggerMode = in_array(getenv('APP_ENV'), ['production', 'staging']) ? Debugger::PRODUCTION : Debugger::DEVELOPMENT;

// Debugger
Debugger::$showBar = $debuggerMode === Debugger::DEVELOPMENT;
Debugger::$strictMode = $debuggerMode === Debugger::DEVELOPMENT;
Debugger::enable($debuggerMode, APP_DIR . '/storage/logs');

if (file_exists(APP_DIR . '/.env')) {
    (new Dotenv(APP_DIR))->overload();
}
